TCP-Chat/Controllers/HistoryLogController.cs
using System.ComponentModel;
using System;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using TCP_Chat.Date;
using TCP_Chat.Models;
using TCP_Chat.ViewModels;

namespace TCP_Chat.Controllers {
    [Authorize]
    public class HistoryLogController : Controller {

        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly AppDbContext _context;

        public HistoryLogController (UserManager<User> userManager, SignInManager<User> signInManager, AppDbContext context) {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }
        public async Task<IActionResult> Index (string date, string namefrom, string nameto, int? history, int page = 1, SortState sortOrder = SortState.NameAsc) {

            int pageSize = 10;
            var userIdFrom = _context.Users.FirstOrDefault (u => u.UserName == namefrom);
            var userIdTo = _context.Users.FirstOrDefault (u => u.UserName == nameto);
            IQueryable<HistoryLog> source = _context.HistoryLogs.Where (a => a.Status == true || a.Status == false)
                .Include (x => x.UserFrom)
                .Include (x => x.UserTo);

            if (userIdFrom != null || userIdTo != null) { //Log Поиск если заданы  и имя и дата

                if (namefrom != null && date != null) {
                    DateTimeOffset dtFrom = DateTime.ParseExact (date, "yyyy-MM-dd", CultureInfo.InvariantCulture);

                    source = source.Where (a => a.UserFromId == userIdFrom.Id && a.Date.Year == dtFrom.Year && a.Date.Day == dtFrom.Day && a.Date.Month == dtFrom.Month && a.Status == true || a.Status == false);

                } else if (!String.IsNullOrEmpty (namefrom)) {

                    source = source.Where (a => a.UserFromId == userIdFrom.Id && a.Status == true || a.Status == false);
                } else if (!String.IsNullOrEmpty (nameto)) {

                    source = source.Where (a => a.UserToId == userIdTo.Id && a.Status == true || a.Status == false);
                } else if (nameto != null && date != null) {

                    DateTimeOffset dtFrom = DateTime.ParseExact (date, "yyyy-MM-dd", CultureInfo.InvariantCulture);

                    source = source.Where (a => a.UserToId == userIdTo.Id && a.Date.Year == dtFrom.Year && a.Date.Day == dtFrom.Day && a.Date.Month == dtFrom.Month && a.Status == true || a.Status == false);
                } else
                    source = source.Where (a => a.Status == true || a.Status == false);

                // сортировка
                switch (sortOrder) {
                    case SortState.NameDesc:
                        source = source.OrderByDescending (s => s.UserFromId);
                        break;
                    case SortState.DateAsc:
                        source = source.OrderBy (s => s.Date.Date);
                        break;
                    case SortState.DateDesc:
                        source = source.OrderByDescending (s => s.Status);
                        break;
                    default:
                        source = source.OrderBy (s => s.UserFromId);
                        break;
                }

                // пагинация
                var count = await source.CountAsync ();
                var items = await source.Skip ((page - 1) * pageSize).Take (pageSize).ToListAsync ();

                PageViewModel pageViewModel = new PageViewModel (count, page, pageSize);
                HistoryLogVM viewModel = new HistoryLogVM {
                    PageViewModel = pageViewModel,
                    SortViewModel = new SortViewModel (sortOrder),
                    FilterViewModel = new FilterViewModel (_context.HistoryLogs.ToList (), date, namefrom, nameto),
                    HistoryLogs = items
                };

            }

            // сортировка
            switch (sortOrder) {
                case SortState.NameDesc:
                    source = source.OrderByDescending (s => s.UserFromId);
                    break;
                case SortState.DateAsc:
                    source = source.OrderBy (s => s.Date.Date);
                    break;
                case SortState.DateDesc:
                    source = source.OrderByDescending (s => s.Status);
                    break;
                default:
                    source = source.OrderBy (s => s.UserFromId);
                    break;
            }

            if (date != null) {
                DateTimeOffset dtFrom = DateTime.ParseExact (date, "yyyy-MM-dd", CultureInfo.InvariantCulture);

                source = source.Where (a => a.Date.Year == dtFrom.Year && a.Date.Day == dtFrom.Day && a.Date.Month == dtFrom.Month && a.Status == true);

            } else {
                source = source.Where (a => a.Status == true || a.Status == false);
            }

            var countAll = await source.CountAsync ();
            var itemsAll = await source.Skip ((page - 1) * pageSize).Take (pageSize).ToListAsync ();

            PageViewModel pageViewModelAll = new PageViewModel (countAll, page, pageSize);
            HistoryLogVM viewModelAll = new HistoryLogVM {
                PageViewModel = pageViewModelAll,
                SortViewModel = new SortViewModel (sortOrder),
                FilterViewModel = new FilterViewModel (_context.HistoryLogs.ToList (), date, namefrom, nameto),
                HistoryLogs = itemsAll
            };

            return View (viewModelAll);

        }
    }
}

TCP-Chat/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<User> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
          method="post" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li><a href="javascript:document.getElementById('logoutForm').submit()"  style="margin-left: 15px; font-size: 15pt;">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a id="registerLink" asp-controller="Account" asp-action="Register" style="margin-right: 10px; font-size: 15pt;"> Register </a></li>
        <li><a id="loginLink" asp-controller="Account" asp-action="Login" style="font-size: 15pt;"> Log in </a></li>
    </ul>
}

TCP-Chat/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using TCP_Chat.Models

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TCP_Chat</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/style.css" />
        <link rel="stylesheet" href="~/css/mycss.css" />
        <link rel="stylesheet" href="~/css/plugins" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TCP_Chat</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" style="font-size: 13pt;" asp-action="Chat2">Домой</a>
                        </li>   
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HistoryLog" style="font-size: 13pt;" asp-action="Index">Лог</a>
                        </li>                           
                    </ul>
                   
                </div>   
                 @if (SignInManager.IsSignedIn(User))
                    {               
                        <a class="nav-link text-dark" style="font-size: 15pt;"> @await Component.InvokeAsync("NameUserComponent")</a>
                    }
                 @await Html.PartialAsync("LoginPartial") 
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>